-- Seed Florida Demo Data for GVTEWAY
-- This migration adds demo data for Music (Artists), Events, Adventures, News, and Shops
-- All data represents Florida markets (Miami, Tampa, Orlando, Jacksonville, etc.)

-- ============================================================================
-- MUSIC / ARTISTS (15+ Florida-based artists)
-- ============================================================================

INSERT INTO artists (name, slug, bio, genre_tags, profile_image_url, verified, created_at) VALUES
('Lynyrd Skynyrd', 'lynyrd-skynyrd', 'Legendary Southern rock band from Jacksonville, known for "Sweet Home Alabama" and "Free Bird"', ARRAY['Rock', 'Southern Rock', 'Classic Rock'], '/artists/lynyrd-skynyrd.jpg', true, NOW()),
('Tom Petty & The Heartbreakers', 'tom-petty-heartbreakers', 'Iconic rock band from Gainesville, fronted by the late Tom Petty', ARRAY['Rock', 'Heartland Rock', 'Classic Rock'], '/artists/tom-petty.jpg', true, NOW()),
('Pitbull', 'pitbull', 'Miami-based rapper and international superstar, known as "Mr. Worldwide"', ARRAY['Hip Hop', 'Latin', 'Pop'], '/artists/pitbull.jpg', true, NOW()),
('Rick Ross', 'rick-ross', 'Miami rapper and founder of Maybach Music Group', ARRAY['Hip Hop', 'Rap'], '/artists/rick-ross.jpg', true, NOW()),
('Flo Rida', 'flo-rida', 'Miami Gardens rapper known for chart-topping hits', ARRAY['Hip Hop', 'Pop', 'Dance'], '/artists/flo-rida.jpg', true, NOW()),
('Backstreet Boys', 'backstreet-boys', 'Orlando-formed boy band, one of the best-selling groups of all time', ARRAY['Pop', 'R&B'], '/artists/backstreet-boys.jpg', true, NOW()),
('NSYNC', 'nsync', 'Orlando-based pop group featuring Justin Timberlake', ARRAY['Pop', 'R&B'], '/artists/nsync.jpg', true, NOW()),
('Ariana Grande', 'ariana-grande', 'Boca Raton native and international pop superstar', ARRAY['Pop', 'R&B'], '/artists/ariana-grande.jpg', true, NOW()),
('Jason Derulo', 'jason-derulo', 'Miami-born singer, songwriter, and dancer', ARRAY['Pop', 'R&B', 'Dance'], '/artists/jason-derulo.jpg', true, NOW()),
('Kodak Black', 'kodak-black', 'Pompano Beach rapper with distinctive Florida sound', ARRAY['Hip Hop', 'Rap'], '/artists/kodak-black.jpg', false, NOW()),
('XXXTentacion', 'xxxtentacion', 'Plantation-based rapper who revolutionized SoundCloud rap', ARRAY['Hip Hop', 'Emo Rap', 'Alternative'], '/artists/xxxtentacion.jpg', true, NOW()),
('Plies', 'plies', 'Fort Myers rapper known for Southern hip hop', ARRAY['Hip Hop', 'Southern Rap'], '/artists/plies.jpg', false, NOW()),
('Trick Daddy', 'trick-daddy', 'Miami rapper and pioneer of Southern hip hop', ARRAY['Hip Hop', 'Southern Rap'], '/artists/trick-daddy.jpg', false, NOW()),
('Trina', 'trina', 'Miami rapper known as the "Diamond Princess"', ARRAY['Hip Hop', 'Rap'], '/artists/trina.jpg', false, NOW()),
('Debbie Harry', 'debbie-harry', 'Miami-born lead singer of Blondie', ARRAY['Rock', 'New Wave', 'Punk'], '/artists/debbie-harry.jpg', true, NOW()),
('Gloria Estefan', 'gloria-estefan', 'Miami Sound Machine legend and Latin music icon', ARRAY['Latin', 'Pop', 'Dance'], '/artists/gloria-estefan.jpg', true, NOW()),
('Enrique Iglesias', 'enrique-iglesias', 'Miami-based Latin pop superstar', ARRAY['Latin', 'Pop'], '/artists/enrique-iglesias.jpg', true, NOW()),
('Yelawolf', 'yelawolf', 'Gadsden-born rapper with Southern rock influences', ARRAY['Hip Hop', 'Southern Rap', 'Rock'], '/artists/yelawolf.jpg', false, NOW());

-- ============================================================================
-- EVENTS (15+ Florida events across major cities)
-- ============================================================================

INSERT INTO events (name, slug, description, event_type, start_date, end_date, venue_name, venue_address, age_restriction, capacity, status, hero_image_url, created_at) VALUES
('Ultra Music Festival', 'ultra-music-festival-2025', 'The world''s premier electronic music festival returns to Miami', 'festival', '2025-03-28 12:00:00+00', '2025-03-30 23:00:00+00', 'Bayfront Park', '{"street": "301 Biscayne Blvd", "city": "Miami", "state": "FL", "zip": "33132"}', '18+', 165000, 'on_sale', '/events/ultra.jpg', NOW()),
('Rolling Loud Miami', 'rolling-loud-miami-2025', 'Hip hop''s biggest festival featuring top rap artists', 'festival', '2025-07-18 14:00:00+00', '2025-07-20 23:00:00+00', 'Hard Rock Stadium', '{"street": "347 Don Shula Dr", "city": "Miami Gardens", "state": "FL", "zip": "33056"}', '18+', 75000, 'on_sale', '/events/rolling-loud.jpg', NOW()),
('Gasparilla Music Festival', 'gasparilla-music-festival-2025', 'Tampa''s premier music and arts festival', 'festival', '2025-03-08 12:00:00+00', '2025-03-09 22:00:00+00', 'Curtis Hixon Waterfront Park', '{"street": "600 N Ashley Dr", "city": "Tampa", "state": "FL", "zip": "33602"}', 'All Ages', 25000, 'on_sale', '/events/gasparilla.jpg', NOW()),
('Okeechobee Music Festival', 'okeechobee-fest-2025', 'Multi-genre music festival in the heart of Florida', 'festival', '2025-03-06 12:00:00+00', '2025-03-09 23:00:00+00', 'Sunshine Grove', '{"street": "7095 NW 160th St", "city": "Okeechobee", "state": "FL", "zip": "34972"}', '18+', 30000, 'on_sale', '/events/okeechobee.jpg', NOW()),
('Tortuga Music Festival', 'tortuga-music-festival-2025', 'Country and rock music on the beach', 'festival', '2025-04-11 12:00:00+00', '2025-04-13 22:00:00+00', 'Fort Lauderdale Beach Park', '{"street": "1100 Seabreeze Blvd", "city": "Fort Lauderdale", "state": "FL", "zip": "33316"}', 'All Ages', 30000, 'on_sale', '/events/tortuga.jpg', NOW()),
('EDC Orlando', 'edc-orlando-2025', 'Electric Daisy Carnival brings electronic music to Orlando', 'festival', '2025-11-07 17:00:00+00', '2025-11-09 02:00:00+00', 'Tinker Field', '{"street": "287 Tampa Ave S", "city": "Orlando", "state": "FL", "zip": "32805"}', '18+', 75000, 'upcoming', '/events/edc-orlando.jpg', NOW()),
('Sunfest', 'sunfest-2025', 'Florida''s largest waterfront music and art festival', 'festival', '2025-05-01 12:00:00+00', '2025-05-04 22:00:00+00', 'Downtown West Palm Beach', '{"street": "101 S Clematis St", "city": "West Palm Beach", "state": "FL", "zip": "33401"}', 'All Ages', 175000, 'upcoming', '/events/sunfest.jpg', NOW()),
('Welcome to Rockville', 'welcome-to-rockville-2025', 'America''s biggest rock festival', 'festival', '2025-05-15 12:00:00+00', '2025-05-18 23:00:00+00', 'Daytona International Speedway', '{"street": "1801 W International Speedway Blvd", "city": "Daytona Beach", "state": "FL", "zip": "32114"}', '18+', 50000, 'upcoming', '/events/rockville.jpg', NOW()),
('III Points', 'iii-points-2025', 'Miami''s cutting-edge music and art festival', 'festival', '2025-10-17 14:00:00+00', '2025-10-19 03:00:00+00', 'Mana Wynwood', '{"street": "318 NW 23rd St", "city": "Miami", "state": "FL", "zip": "33127"}', '18+', 15000, 'upcoming', '/events/iii-points.jpg', NOW()),
('Hulaween', 'hulaween-2025', 'String Cheese Incident''s Halloween music festival', 'festival', '2025-10-30 12:00:00+00', '2025-11-02 23:00:00+00', 'Spirit of the Suwannee Music Park', '{"street": "3076 95th Dr", "city": "Live Oak", "state": "FL", "zip": "32060"}', '18+', 20000, 'upcoming', '/events/hulaween.jpg', NOW()),
('Sunset Music Festival', 'sunset-music-festival-2025', 'Tampa''s premier EDM festival', 'festival', '2025-05-24 14:00:00+00', '2025-05-25 23:00:00+00', 'Raymond James Stadium', '{"street": "4201 N Dale Mabry Hwy", "city": "Tampa", "state": "FL", "zip": "33607"}', '18+', 50000, 'upcoming', '/events/sunset.jpg', NOW()),
('Jacksonville Jazz Festival', 'jacksonville-jazz-festival-2025', 'Free outdoor jazz festival in downtown Jacksonville', 'festival', '2025-05-23 12:00:00+00', '2025-05-25 22:00:00+00', 'Downtown Jacksonville', '{"street": "300 Water St", "city": "Jacksonville", "state": "FL", "zip": "32202"}', 'All Ages', 100000, 'upcoming', '/events/jax-jazz.jpg', NOW()),
('Florida Strawberry Festival', 'florida-strawberry-festival-2025', 'Music, rides, and strawberry shortcake', 'festival', '2025-02-27 10:00:00+00', '2025-03-09 22:00:00+00', 'Florida Strawberry Festival Grounds', '{"street": "2402 W Reynolds St", "city": "Plant City", "state": "FL", "zip": "33563"}', 'All Ages', 500000, 'upcoming', '/events/strawberry.jpg', NOW()),
('Miami Music Week', 'miami-music-week-2025', 'Week-long electronic music celebration', 'festival', '2025-03-24 12:00:00+00', '2025-03-30 06:00:00+00', 'Various Venues', '{"city": "Miami", "state": "FL"}', '21+', 300000, 'on_sale', '/events/mmw.jpg', NOW()),
('Suwannee Hulaween', 'suwannee-hulaween-2025', 'Immersive music and arts experience', 'festival', '2025-10-30 12:00:00+00', '2025-11-02 23:00:00+00', 'Spirit of the Suwannee Music Park', '{"street": "3076 95th Dr", "city": "Live Oak", "state": "FL", "zip": "32060"}', '18+', 20000, 'upcoming', '/events/suwannee.jpg', NOW()),
('Riptide Music Festival', 'riptide-music-festival-2025', 'Fort Lauderdale beach music festival', 'festival', '2025-12-06 12:00:00+00', '2025-12-07 22:00:00+00', 'Fort Lauderdale Beach', '{"street": "1100 Seabreeze Blvd", "city": "Fort Lauderdale", "state": "FL", "zip": "33316"}', 'All Ages', 25000, 'upcoming', '/events/riptide.jpg', NOW());

-- ============================================================================
-- ADVENTURES (15+ Florida outdoor experiences)
-- ============================================================================

INSERT INTO adventures (name, slug, description, adventure_type, location_name, location_address, location_coordinates, city, state, price_range, min_price, max_price, duration_hours, difficulty_level, max_participants, hero_image_url, amenities, tags, status, featured, created_at) VALUES
('Rainbow Springs Kayaking', 'rainbow-springs-kayaking', 'Paddle through crystal-clear spring waters surrounded by lush Florida nature', 'kayaking', 'Rainbow Springs State Park', '{"street": "19158 SW 81st Pl Rd", "city": "Dunnellon", "state": "FL", "zip": "34432"}', point(-82.4348, 29.1011), 'Dunnellon', 'FL', '$$', 35.00, 65.00, 3.0, 'easy', 20, '/adventures/rainbow-springs.jpg', ARRAY['parking', 'restrooms', 'equipment_rental'], ARRAY['water', 'outdoor', 'family-friendly', 'nature'], 'active', true, NOW()),
('Everglades Airboat Tour', 'everglades-airboat-tour', 'High-speed adventure through the River of Grass, spot alligators and wildlife', 'tours', 'Everglades National Park', '{"street": "40001 State Road 9336", "city": "Homestead", "state": "FL", "zip": "33034"}', point(-80.4773, 25.3744), 'Homestead', 'FL', '$$', 45.00, 85.00, 1.5, 'easy', 12, '/adventures/everglades.jpg', ARRAY['parking', 'restrooms', 'food'], ARRAY['water', 'wildlife', 'family-friendly', 'adventure'], 'active', true, NOW()),
('Key West Snorkeling', 'key-west-snorkeling', 'Explore vibrant coral reefs and tropical fish in crystal waters', 'water', 'Key West', '{"city": "Key West", "state": "FL", "zip": "33040"}', point(-81.7800, 24.5551), 'Key West', 'FL', '$$$', 75.00, 125.00, 4.0, 'moderate', 15, '/adventures/key-west-snorkel.jpg', ARRAY['equipment_rental', 'food', 'restrooms'], ARRAY['water', 'ocean', 'marine-life', 'adventure'], 'active', true, NOW()),
('Myakka River State Park Hiking', 'myakka-hiking', 'Hike through one of Florida''s oldest and largest state parks', 'hiking', 'Myakka River State Park', '{"street": "13208 State Road 72", "city": "Sarasota", "state": "FL", "zip": "34241"}', point(-82.3081, 27.2350), 'Sarasota', 'FL', '$', 6.00, 15.00, 2.5, 'moderate', 30, '/adventures/myakka.jpg', ARRAY['parking', 'restrooms', 'camping'], ARRAY['hiking', 'nature', 'wildlife', 'outdoor'], 'active', false, NOW()),
('Ichetucknee Springs Tubing', 'ichetucknee-tubing', 'Float down pristine spring-fed river on inner tubes', 'water', 'Ichetucknee Springs State Park', '{"street": "12087 SW US Highway 27", "city": "Fort White", "state": "FL", "zip": "32038"}', point(-82.7617, 29.9833), 'Fort White', 'FL', '$', 8.00, 20.00, 3.0, 'easy', 50, '/adventures/ichetucknee.jpg', ARRAY['parking', 'restrooms', 'equipment_rental'], ARRAY['water', 'family-friendly', 'summer', 'relaxing'], 'active', false, NOW()),
('Dry Tortugas Snorkeling', 'dry-tortugas-snorkeling', 'Remote island paradise with historic fort and pristine reefs', 'water', 'Dry Tortugas National Park', '{"city": "Key West", "state": "FL"}', point(-82.8732, 24.6285), 'Key West', 'FL', '$$$$', 185.00, 250.00, 8.0, 'moderate', 20, '/adventures/dry-tortugas.jpg', ARRAY['food', 'equipment_rental'], ARRAY['water', 'ocean', 'historic', 'adventure'], 'active', true, NOW()),
('Wekiwa Springs Kayaking', 'wekiwa-springs-kayaking', 'Paddle through natural springs near Orlando', 'kayaking', 'Wekiwa Springs State Park', '{"street": "1800 Wekiwa Cir", "city": "Apopka", "state": "FL", "zip": "32712"}', point(-81.4431, 28.7097), 'Apopka', 'FL', '$$', 30.00, 55.00, 2.5, 'easy', 15, '/adventures/wekiwa.jpg', ARRAY['parking', 'restrooms', 'equipment_rental', 'camping'], ARRAY['water', 'kayaking', 'nature', 'family-friendly'], 'active', false, NOW()),
('St. Augustine Ghost Tour', 'st-augustine-ghost-tour', 'Explore America''s oldest city and its haunted history', 'tours', 'Historic Downtown St. Augustine', '{"street": "4 Granada St", "city": "St. Augustine", "state": "FL", "zip": "32084"}', point(-81.3124, 29.8987), 'St. Augustine', 'FL', '$$', 25.00, 40.00, 1.5, 'easy', 25, '/adventures/st-augustine-ghost.jpg', ARRAY['restrooms'], ARRAY['historic', 'walking', 'nightlife', 'culture'], 'active', false, NOW()),
('Blue Spring Manatee Tour', 'blue-spring-manatee', 'See hundreds of manatees in their natural winter habitat', 'wildlife', 'Blue Spring State Park', '{"street": "2100 W French Ave", "city": "Orange City", "state": "FL", "zip": "32763"}', point(-81.3431, 28.9450), 'Orange City', 'FL', '$', 6.00, 25.00, 2.0, 'easy', 40, '/adventures/blue-spring.jpg', ARRAY['parking', 'restrooms', 'food'], ARRAY['wildlife', 'nature', 'family-friendly', 'winter'], 'active', false, NOW()),
('Devil''s Den Scuba Diving', 'devils-den-diving', 'Dive in an underground spring inside a prehistoric cave', 'diving', 'Devil''s Den', '{"street": "5390 NE 180th Ave", "city": "Williston", "state": "FL", "zip": "32696"}', point(-82.5931, 29.4914), 'Williston', 'FL', '$$$', 65.00, 95.00, 3.0, 'challenging', 10, '/adventures/devils-den.jpg', ARRAY['equipment_rental', 'restrooms', 'parking'], ARRAY['diving', 'underwater', 'adventure', 'unique'], 'active', true, NOW()),
('Caladesi Island Kayaking', 'caladesi-island-kayaking', 'Paddle to pristine barrier island beach', 'kayaking', 'Caladesi Island State Park', '{"street": "1 Causeway Blvd", "city": "Dunedin", "state": "FL", "zip": "34698"}', point(-82.8156, 28.0297), 'Dunedin', 'FL', '$$', 35.00, 60.00, 3.5, 'moderate', 12, '/adventures/caladesi.jpg', ARRAY['equipment_rental', 'restrooms', 'beach'], ARRAY['kayaking', 'beach', 'island', 'nature'], 'active', false, NOW()),
('Corkscrew Swamp Boardwalk', 'corkscrew-swamp', 'Walk through ancient cypress forest on elevated boardwalk', 'hiking', 'Corkscrew Swamp Sanctuary', '{"street": "375 Sanctuary Rd W", "city": "Naples", "state": "FL", "zip": "34120"}', point(-81.5981, 26.3753), 'Naples', 'FL', '$', 15.00, 20.00, 2.0, 'easy', 50, '/adventures/corkscrew.jpg', ARRAY['parking', 'restrooms'], ARRAY['nature', 'wildlife', 'walking', 'family-friendly'], 'active', false, NOW()),
('Ginnie Springs Diving', 'ginnie-springs-diving', 'World-class spring diving and snorkeling', 'diving', 'Ginnie Springs', '{"street": "7300 NE Ginnie Springs Rd", "city": "High Springs", "state": "FL", "zip": "32643"}', point(-82.8550, 29.8383), 'High Springs', 'FL', '$$', 40.00, 75.00, 4.0, 'moderate', 20, '/adventures/ginnie-springs.jpg', ARRAY['camping', 'equipment_rental', 'restrooms', 'food'], ARRAY['diving', 'water', 'camping', 'adventure'], 'active', false, NOW()),
('Shark Valley Bike Tour', 'shark-valley-bike', 'Bike through Everglades wildlife on 15-mile loop', 'biking', 'Shark Valley', '{"street": "36000 SW 8th St", "city": "Miami", "state": "FL", "zip": "33194"}', point(-80.7631, 25.7589), 'Miami', 'FL', '$', 9.00, 25.00, 3.0, 'moderate', 30, '/adventures/shark-valley.jpg', ARRAY['parking', 'restrooms', 'equipment_rental'], ARRAY['biking', 'wildlife', 'nature', 'outdoor'], 'active', false, NOW()),
('Biscayne Bay Paddleboarding', 'biscayne-paddleboard', 'Stand-up paddleboard through mangrove tunnels', 'paddleboarding', 'Biscayne National Park', '{"street": "9700 SW 328th St", "city": "Homestead", "state": "FL", "zip": "33033"}', point(-80.3281, 25.4900), 'Homestead', 'FL', '$$', 45.00, 70.00, 2.5, 'easy', 10, '/adventures/biscayne-paddle.jpg', ARRAY['equipment_rental', 'parking', 'restrooms'], ARRAY['paddleboarding', 'water', 'mangroves', 'nature'], 'active', false, NOW()),
('Ocala National Forest Hiking', 'ocala-forest-hiking', 'Explore Florida''s largest national forest', 'hiking', 'Ocala National Forest', '{"street": "45621 State Road 19", "city": "Altoona", "state": "FL", "zip": "32702"}', point(-81.6431, 29.0450), 'Altoona', 'FL', '$', 0.00, 10.00, 4.0, 'moderate', 40, '/adventures/ocala-forest.jpg', ARRAY['parking', 'camping', 'restrooms'], ARRAY['hiking', 'camping', 'nature', 'forest'], 'active', false, NOW());

-- ============================================================================
-- NEWS ARTICLES (15+ Florida entertainment/culture news)
-- ============================================================================

INSERT INTO news_articles (title, slug, excerpt, content, image_url, category, author, published, published_at, created_at) VALUES
('Ultra Music Festival Announces 2025 Lineup', 'ultra-2025-lineup', 'Miami''s premier EDM festival reveals star-studded artist roster', 'Ultra Music Festival has announced its highly anticipated 2025 lineup, featuring top electronic music artists from around the world...', '/news/ultra-lineup.jpg', 'Music', 'Sarah Martinez', true, NOW() - interval '2 days', NOW()),
('New Music Venue Opens in Wynwood', 'wynwood-venue-opens', 'Miami''s arts district welcomes state-of-the-art performance space', 'A new 2,000-capacity music venue has opened in Miami''s Wynwood Arts District, adding to the neighborhood''s growing cultural scene...', '/news/wynwood-venue.jpg', 'Venues', 'Michael Chen', true, NOW() - interval '5 days', NOW()),
('Florida Artists Dominate Billboard Charts', 'florida-artists-billboard', 'Sunshine State musicians continue to make waves nationally', 'Florida-based artists are having a moment on the Billboard charts, with multiple acts from Miami, Orlando, and Tampa breaking into the top 100...', '/news/billboard-florida.jpg', 'Music', 'Jessica Williams', true, NOW() - interval '1 week', NOW()),
('Tampa Bay Music Scene Experiencing Renaissance', 'tampa-music-renaissance', 'Local venues and artists driving cultural revival', 'Tampa''s music scene is experiencing unprecedented growth, with new venues opening and local artists gaining national attention...', '/news/tampa-music.jpg', 'Culture', 'David Rodriguez', true, NOW() - interval '10 days', NOW()),
('Rolling Loud Expands to Three Days', 'rolling-loud-expansion', 'Hip hop festival announces extended 2025 format', 'Rolling Loud Miami will expand to a three-day format in 2025, featuring over 100 artists across multiple stages...', '/news/rolling-loud-expand.jpg', 'Festivals', 'Amanda Johnson', true, NOW() - interval '2 weeks', NOW()),
('Jacksonville Jazz Festival Sets Record Attendance', 'jax-jazz-record', 'Free festival draws largest crowd in its history', 'The Jacksonville Jazz Festival broke attendance records this year, drawing over 150,000 music fans to downtown Jacksonville...', '/news/jax-jazz-record.jpg', 'Festivals', 'Robert Taylor', true, NOW() - interval '3 weeks', NOW()),
('Miami Music Week 2025 Dates Announced', 'miami-music-week-2025', 'Electronic music takeover returns to South Beach', 'Miami Music Week will return March 24-30, 2025, bringing hundreds of events and thousands of artists to South Florida...', '/news/mmw-2025.jpg', 'Music', 'Sarah Martinez', true, NOW() - interval '1 month', NOW()),
('Orlando Venue District Gets Major Upgrade', 'orlando-venue-upgrade', 'Downtown entertainment complex undergoes renovation', 'Orlando''s downtown venue district is receiving a $50 million upgrade, including renovations to multiple performance spaces...', '/news/orlando-upgrade.jpg', 'Venues', 'Michael Chen', true, NOW() - interval '5 weeks', NOW()),
('Florida Music Education Programs Expand', 'florida-music-education', 'New initiatives bring music to underserved communities', 'Statewide music education programs are expanding, providing instruments and instruction to students across Florida...', '/news/music-education.jpg', 'Culture', 'Jessica Williams', true, NOW() - interval '6 weeks', NOW()),
('Gasparilla Music Festival Adds Second Weekend', 'gasparilla-second-weekend', 'Tampa festival doubles capacity with new dates', 'Due to overwhelming demand, Gasparilla Music Festival will add a second weekend in 2025...', '/news/gasparilla-expand.jpg', 'Festivals', 'David Rodriguez', true, NOW() - interval '2 months', NOW()),
('St. Augustine Amphitheater Season Announced', 'st-augustine-amphitheater', 'Historic city''s premier venue reveals summer lineup', 'The St. Augustine Amphitheatre has announced its summer 2025 season, featuring major touring acts...', '/news/st-aug-amphitheater.jpg', 'Venues', 'Amanda Johnson', true, NOW() - interval '10 weeks', NOW()),
('Florida Venues Implement New Sustainability Practices', 'venues-sustainability', 'Major concert spaces go green', 'Florida''s largest music venues are implementing new sustainability practices, reducing environmental impact...', '/news/venues-green.jpg', 'Culture', 'Robert Taylor', true, NOW() - interval '3 months', NOW()),
('Emerging Artists Showcase Coming to Miami', 'miami-emerging-artists', 'New platform highlights local talent', 'A new monthly showcase series will spotlight emerging Florida artists at venues across Miami...', '/news/emerging-artists.jpg', 'Music', 'Sarah Martinez', true, NOW() - interval '4 months', NOW()),
('Fort Lauderdale Beach Gets New Concert Series', 'fort-lauderdale-concerts', 'Free summer concerts announced for beachfront', 'Fort Lauderdale will host a free summer concert series on the beach, featuring local and national acts...', '/news/ftl-concerts.jpg', 'Events', 'Michael Chen', true, NOW() - interval '5 months', NOW()),
('Florida Music Industry Report Shows Growth', 'florida-music-industry', 'State''s music economy reaches new heights', 'A new report shows Florida''s music industry contributed $3.8 billion to the state economy in 2024...', '/news/music-industry.jpg', 'Business', 'Jessica Williams', true, NOW() - interval '6 months', NOW());

-- Update counts and timestamps
UPDATE artists SET updated_at = NOW();
UPDATE events SET updated_at = NOW();
UPDATE adventures SET updated_at = NOW();
UPDATE news_articles SET updated_at = NOW();
